- include_tasks: boot_args.yml
- name: selinux in permissive, for now
  become: true
  selinux:
    policy: targeted
    state: permissive
  register: selinux_state
- reboot:
  become: true
  when: ( selinux_state.changed or grub_args.changed )
- name: load the bridge and overlay  modules
  become: true
  modprobe:
    name: "{{ item }}"
    state: present
  with_items: "{{ required_kernel_modules }}"
- name: on boot too
  become: true
  lineinfile:
    line: "{{ item }}"
    path: /etc/modules-load.d/container_host.conf
    create: yes
  with_items: "{{ required_kernel_modules }}"
- name: adjust sysctl parameters 
  become: true
  sysctl:
    name: "{{ item.p }}"
    value: "{{ item.v }}"
    reload: yes
    sysctl_file: /etc/sysctl.d/kube_recs.conf
  with_items: "{{ sysctl_parameters }}"
- name: configure hostfile
  become: true
  template:
    src: templates/hostfile.j2
    dest: /etc/hosts
- name: tell NetworkManager to leave calico interfaces alone
  become: true
  copy:
    content: |
      [keyfile]
      unmanaged-devices=interface-name:cali*;interface-name:tunl*
    dest: /etc/NetworkManager/conf.d/calico.conf
  register: nm_calico_settings
  when: ( cni_plugin == 'calico' )
- name: restart NetworkManager if neeeded
  become: true
  service:
    name: NetworkManager
    state: restarted
