- name: don't pull kube from stock repos
  become: true
  ini_file:
    path: "/etc/yum.repos.d/{{ item.filename }}.repo"
    section: "{{ item.reponame }}"
    option: exclude
    value: "*kube* *etcd* *docker*"
  with_items: "{{ [ { 'filename': 'fedora', 'reponame': 'fedora' }, { 'filename': 'fedora-updates', 'reponame': 'updates' } ] }}"
- name:  register repo signing keys
  become: true
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items: 
    - https://packages.cloud.google.com/yum/doc/yum-key.gpg 
    - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    - https://download.docker.com/linux/fedora/gpg 
- name: configure upstream kube repo
  become: true
  yum_repository:
    name: kuberentes
    state: present
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    description: kubernetes upstream packages
    enabled: yes
    gpgcheck: yes
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg 
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
- name: configure docker fedora-ce repo
  become: true
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    state: present
    baseurl: "https://download.docker.com/linux/fedora/$releasever/$basearch/stable"
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/fedora/gpg
